# Generated by Django 3.2.25 on 2026-01-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'custom_roles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=100)),
                ('actions', models.JSONField(default=list)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_list', to='roles.customrole')),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(fields=['name'], name='custom_role_name_bfb8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(fields=['is_system'], name='custom_role_is_syst_144b58_idx'),
        ),
    ]
