# Generated by Django 5.2.7 on 2025-11-02 17:52

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="Password",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("title", models.CharField(max_length=255)),
				("url", models.CharField(max_length=255)),
				("password_hash", models.TextField()),
				("note", models.TextField(blank=True, null=True)),
			],
		),
		migrations.CreateModel(
			name="GroupMembership",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"role",
					models.CharField(
						choices=[("R", "Read"), ("RW", "Read & Write")],
						default="R",
						max_length=3,
					),
				),
				("created_at", models.DateTimeField(auto_now_add=True)),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="group_memberships",
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				"verbose_name": "Group membership",
				"verbose_name_plural": "Group memberships",
			},
		),
		migrations.CreateModel(
			name="AccessLog",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"action",
					models.CharField(
						choices=[
							("view", "View page"),
							("reveal", "Reveal password"),
							("create", "Create"),
							("change", "Change"),
							("delete", "Delete"),
						],
						max_length=16,
					),
				),
				("timestamp", models.DateTimeField(auto_now_add=True)),
				(
					"ip_address",
					models.GenericIPAddressField(blank=True, null=True),
				),
				("user_agent", models.TextField(blank=True, null=True)),
				("extra", models.TextField(blank=True, null=True)),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.DO_NOTHING,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"password",
					models.ForeignKey(
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name="access_logs",
						to="passwords.password",
					),
				),
			],
			options={
				"ordering": ("-timestamp",),
			},
		),
		migrations.CreateModel(
			name="PasswordGroup",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("name", models.CharField(max_length=255, unique=True)),
				("description", models.TextField(blank=True, null=True)),
				(
					"members",
					models.ManyToManyField(
						blank=True,
						related_name="password_groups",
						through="passwords.GroupMembership",
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					"passwords",
					models.ManyToManyField(
						blank=True,
						related_name="groups",
						to="passwords.password",
					),
				),
			],
		),
		migrations.AddField(
			model_name="groupmembership",
			name="group",
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="memberships",
				to="passwords.passwordgroup",
			),
		),
		migrations.AlterUniqueTogether(
			name="groupmembership",
			unique_together={("user", "group")},
		),
	]
