# Generated by Django 5.2.7 on 2025-11-02 19:45

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("passwords", "0001_initial"),
	]

	operations = [
		migrations.RenameField(
			model_name="password",
			old_name="password_hash",
			new_name="password",
		),
	]
