# Generated by Django 5.2.7 on 2025-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("passwords", "0002_rename_password_hash_password_password"),
	]

	operations = [
		migrations.AlterField(
			model_name="password",
			name="url",
			field=models.CharField(max_length=255, null=True),
		),
	]
