# Generated by Django 5.2.7 on 2025-11-03 16:58

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("passwords", "0004_passwordintrash_password_in_trash"),
	]

	operations = [
		migrations.AlterField(
			model_name="accesslog",
			name="password",
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="access_logs",
				to="passwords.password",
			),
		),
	]
