# Generated by Django 5.2.7 on 2025-11-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("passwords", "0006_alter_passwordintrash_options_alter_password_url"),
	]

	operations = [
		migrations.CreateModel(
			name="Tag",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("name", models.CharField(max_length=127, unique=True)),
			],
		),
		migrations.AlterModelOptions(
			name="accesslog",
			options={
				"ordering": ("-timestamp",),
				"verbose_name": "Access log",
				"verbose_name_plural": "Access logs",
			},
		),
		migrations.AlterModelOptions(
			name="password",
			options={
				"verbose_name": "Password",
				"verbose_name_plural": "passwords",
			},
		),
		migrations.AlterModelOptions(
			name="passwordgroup",
			options={
				"verbose_name": "Password Group",
				"verbose_name_plural": "Password Groups",
			},
		),
		migrations.AlterModelOptions(
			name="passwordintrash",
			options={"verbose_name": "Trash", "verbose_name_plural": "Trash"},
		),
		migrations.AddField(
			model_name="password",
			name="tags",
			field=models.ManyToManyField(
				blank=True, null=True, to="passwords.tag"
			),
		),
	]
