# Generated by Django 3.2.25 on 2026-01-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_passwords', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_passwords', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_entries', to='vaults.vault')),
            ],
            options={
                'db_table': 'passwords',
            },
        ),
        migrations.CreateModel(
            name='PasswordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=200)),
                ('password', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_password_versions', to=settings.AUTH_USER_MODEL)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='passwords.passwordentry')),
            ],
            options={
                'db_table': 'password_versions',
            },
        ),
        migrations.AddIndex(
            model_name='passwordversion',
            index=models.Index(fields=['version'], name='password_ve_version_9aa21c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordversion',
            index=models.Index(fields=['created_at'], name='password_ve_created_408aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['title'], name='passwords_title_64e531_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['login'], name='passwords_login_319d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['is_deleted'], name='passwords_is_dele_12cd8d_idx'),
        ),
    ]
