# Generated by Django 3.2.25 on 2026-01-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vaults',
            },
        ),
        migrations.CreateModel(
            name='VaultAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование'), ('admin', 'Администратор')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_accesses', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='vaults.vault')),
            ],
            options={
                'db_table': 'vault_accesses',
                'unique_together': {('vault', 'user')},
            },
        ),
        migrations.AddField(
            model_name='vault',
            name='accesses',
            field=models.ManyToManyField(related_name='accessible_vaults', through='vaults.VaultAccess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vault',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_vaults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['name'], name='vaults_name_ff8b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='vault',
            index=models.Index(fields=['is_deleted'], name='vaults_is_dele_6b5a13_idx'),
        ),
    ]
