# Generated by Django 5.2.10 on 2026-01-25 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='accesses',
            field=models.ManyToManyField(related_name='accessible_vaults', through='vaults.VaultAccess', through_fields=('vault', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
